Eslint and other minor fix
appwex/react-ui-components pull request #23
Opened 2022-12-04 19:54 UTC by mrxshinji

1. Configured eslint to be less aggressive
2. fixed import for ButtonStory and re-lint the rest

2022-12-04 21:46 UTC, aftabrehan requested changes
Excellent PR, @mrxshinji 💪 🚀 💯 

Just needs a minor fix and then it's good to go 🚀

2022-12-04 21:46 UTC, aftabrehan commented on src/components/notifications/notifications.jsx
> +  console.log(notificationData);
Please, make sure to remove unused comments.

2022-12-05 04:39 UTC, mrxshinji commented
done changes

2022-12-05 04:42 UTC, aftabrehan approved these changes
Excellent PR, @mrxshinji 💪 🚀 💯

2022-12-05 04:42 UTC, merged