Add Notification-Bar Component
appwex/react-ui-components pull request #26
Opened 2022-12-05 09:36 UTC by mrxshinji

Fixed #19

# Added Notification component route:
  ```path: 'components/notification',```

## set font-family, font style and box-sizing @ index.css
 ```
box-sizing: border-box;
font-family: 'Inter';
font-style: normal;
```

![image](https://user-images.githubusercontent.com/95459307/205603667-11a8ce94-8794-47b5-b97f-3b225fd9f001.png)

2022-12-05 18:32 UTC, aftabrehan requested changes
Excellent PR, @mrxshinji 💪 🚀 💯  Again, I'm impressed with your work, I cannot see any bug in the code, which is good. I've requested some code-writing suggestions for you. 

Also try using the short name of a branch `ruc/mrxshinji/add-notification-bar-component`  can be`ruc/mrxshinji/notification-bar`

Thank you 🙏

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notificationBar.css
> +  border-left: 2px solid #f2f2f7;
Only have a blank line between selectors.

```suggestion
  position: relative;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  padding: 0px;
  gap: 15px;
  border-left: 2px solid #f2f2f7;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notificationBar.css
> +  background: rgba(88, 86, 214, 0.1);
```suggestion
  height: 40px;
  background: rgba(88, 86, 214, 0.1);
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notificationBar.css
> +  width: 246px;
```suggestion
  gap: 5px;
  width: 246px;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notificationBar.css
> +  color: #1c1c1e;
```suggestion
  font-size: 13px;
  color: #1c1c1e;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notificationBar.css
> +  color: #8E8E93;
```suggestion
  line-height: 15px;
  color: #8E8E93;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notifications.css
> +  position: absolute;
```suggestion
  gap: 30px;
  position: absolute;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notifications.css
> +  background: #ffffff;
```suggestion
  top: 226px;
  background: #ffffff;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notifications.css
> +  font-weight: 600;
```suggestion
  align-items: center;
  width: 19px;
  height: 19px;
  background: #5856d6;
  border-radius: 50%;
  font-weight: 600;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notifications.css
> +  background: #5856d6;
```suggestion
  gap: 10px;
  width: 100%;
  height: 64px;
  background: #5856d6;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notifications.css
> +.notification-sub-text span {
```suggestion
}

.notification-sub-text span {
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notifications.css
> +  color: white;
```suggestion
  line-height: 16px;
  color: white;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/components/notifications/notifications.css
> +  color: #d1d1d6;
```suggestion
  line-height: 15px;
  color: #d1d1d6;
```

2022-12-05 18:32 UTC, aftabrehan commented on src/index.js
> +        path: 'components/notification',
Just use a single flow to display components.

```suggestion
        path: 'stories/notification',
```

2022-12-05 18:32 UTC, aftabrehan commented on src/routes/notification-page/index.jsx
> +const NotificationPage = () => {
`NotificationStory` make sense.

```suggestion
const NotificationStory = () => {
```

2022-12-05 18:32 UTC, aftabrehan commented on src/routes/notification-page/index.jsx
> +    </div>
Any specific reason for wrapping it in a `div`, as I can see no classes on it?

```suggestion
     <Notifications />
```

2022-12-06 04:42 UTC, mrxshinji commented
[added hover effect and changes as requested]
(https://github.com/appwex/react-ui-components/pull/26/commits/c737226ce9cc61327d956eda889091e48007d3e1)

2022-12-06 05:06 UTC, mrxshinji commented
https://github.com/appwex/react-ui-components/pull/26/commits/2b13492a3aadbb5bb7fecb7455d2f182a0bbc692 
Added link to component

2022-12-06 05:14 UTC, aftabrehan approved these changes
Excellent PR, @mrxshinji 💪 🚀 💯

2022-12-06 05:15 UTC, merged