Ruc/header search bar fixes
appwex/react-ui-components pull request #70
Opened 2022-12-14 09:57 UTC by whalay

I made the changes specified in the review.
![localhost_3000_ (1)](https://user-images.githubusercontent.com/35483419/207564294-ef5ec46b-e4a7-4294-a1af-25cfc957a5e4.png)
![localhost_3000_ (1)](https://user-images.githubusercontent.com/35483419/207564473-d31caa79-6f12-4fa2-8b36-2b09253d502f.png)

2022-12-14 09:59 UTC, abdulmaleekadams commented
@aftabrehan  Kindly review

2022-12-14 10:22 UTC, mrxshinji commented on src/routes/card-payment/payment.css
> +    width: 100%;
This part is not fixed yet

2022-12-14 10:23 UTC, mrxshinji requested changes
Changes requested not complete

2022-12-17 17:33 UTC, mrxshinji approved these changes

2022-12-17 17:36 UTC, merged

2022-12-18 09:00 UTC, aftabrehan approved these changes
Excellent PR, @whalay 💪 💯 🚀